// 기본 와펜 세트 목록 — tools/wappen-seed/build.mjs 가 생성한다. 직접 수정하지 말 것.
// 모든 그림은 tools/wappen-seed/designs.mjs 에서 코드로 그린 원본(CC0). 서버(functions/wappen-api.js admin_seed_items)와 관리자 화면이 같은 파일을 import.
export const SEED_VERSION = 1;
export const SEED_ITEMS = [
    {"key": "star", "name": "별", "category": "도형·기호", "tags": ["반짝", "노랑", "밤"], "file": "star.png", "w": 862, "h": 821},
    {"key": "heart", "name": "하트", "category": "도형·기호", "tags": ["사랑", "핑크", "러브"], "file": "heart.png", "w": 824, "h": 721},
    {"key": "bolt", "name": "번개", "category": "도형·기호", "tags": ["번쩍", "에너지", "노랑"], "file": "bolt.png", "w": 596, "h": 924},
    {"key": "rainbow", "name": "무지개", "category": "도형·기호", "tags": ["하늘", "행운", "컬러"], "file": "rainbow.png", "w": 950, "h": 473},
    {"key": "cloud", "name": "구름", "category": "도형·기호", "tags": ["하늘", "구름", "몽글"], "file": "cloud.png", "w": 794, "h": 374},
    {"key": "sun", "name": "해", "category": "도형·기호", "tags": ["햇빛", "여름", "따뜻"], "file": "sun.png", "w": 986, "h": 986},
    {"key": "moon", "name": "달", "category": "도형·기호", "tags": ["밤", "졸려", "노랑"], "file": "moon.png", "w": 443, "h": 842},
    {"key": "sparkle", "name": "반짝이", "category": "도형·기호", "tags": ["반짝", "별", "마법"], "file": "sparkle.png", "w": 914, "h": 914},
    {"key": "flame", "name": "불꽃", "category": "도형·기호", "tags": ["불타요", "뜨거워", "열정"], "file": "flame.png", "w": 658, "h": 894},
    {"key": "gem", "name": "보석", "category": "도형·기호", "tags": ["다이아", "반짝", "파랑"], "file": "gem.png", "w": 658, "h": 648},
    {"key": "cat", "name": "고양이", "category": "동물", "tags": ["야옹", "귀여워", "동물"], "file": "cat.png", "w": 742, "h": 729},
    {"key": "dog", "name": "강아지", "category": "동물", "tags": ["멍멍", "귀여워", "동물"], "file": "dog.png", "w": 780, "h": 596},
    {"key": "bear", "name": "곰", "category": "동물", "tags": ["곰돌이", "귀여워", "동물"], "file": "bear.png", "w": 760, "h": 729},
    {"key": "bunny", "name": "토끼", "category": "동물", "tags": ["깡총", "귀여워", "동물"], "file": "bunny.png", "w": 678, "h": 913},
    {"key": "frog", "name": "개구리", "category": "동물", "tags": ["개굴", "초록", "동물"], "file": "frog.png", "w": 780, "h": 729},
    {"key": "penguin", "name": "펭귄", "category": "동물", "tags": ["뒤뚱", "겨울", "동물"], "file": "penguin.png", "w": 658, "h": 817},
    {"key": "chick", "name": "병아리", "category": "동물", "tags": ["삐약", "노랑", "아기"], "file": "chick.png", "w": 698, "h": 797},
    {"key": "pig", "name": "돼지", "category": "동물", "tags": ["꿀꿀", "핑크", "동물"], "file": "pig.png", "w": 698, "h": 719},
    {"key": "panda", "name": "판다", "category": "동물", "tags": ["대나무", "흑백", "동물"], "file": "panda.png", "w": 720, "h": 719},
    {"key": "fox", "name": "여우", "category": "동물", "tags": ["주황", "숲", "동물"], "file": "fox.png", "w": 698, "h": 801},
    {"key": "dino", "name": "공룡", "category": "동물", "tags": ["초록", "귀여워", "쥬라기"], "file": "dino.png", "w": 883, "h": 750},
    {"key": "note", "name": "음표", "category": "음악", "tags": ["멜로디", "노래", "보라"], "file": "note.png", "w": 470, "h": 734},
    {"key": "guitar", "name": "기타", "category": "음악", "tags": ["통기타", "밴드", "연주"], "file": "guitar.png", "w": 454, "h": 944},
    {"key": "drum", "name": "드럼", "category": "음악", "tags": ["밴드", "둥둥", "리듬"], "file": "drum.png", "w": 658, "h": 650},
    {"key": "headphones", "name": "헤드폰", "category": "음악", "tags": ["음악감상", "파랑", "힙"], "file": "headphones.png", "w": 842, "h": 701},
    {"key": "mic", "name": "마이크", "category": "음악", "tags": ["노래", "보컬", "라이브"], "file": "mic.png", "w": 494, "h": 873},
    {"key": "vinyl", "name": "LP판", "category": "음악", "tags": ["레코드", "빈티지", "음악"], "file": "vinyl.png", "w": 904, "h": 904},
    {"key": "cassette", "name": "카세트", "category": "음악", "tags": ["테이프", "레트로", "90s"], "file": "cassette.png", "w": 842, "h": 596},
    {"key": "piano", "name": "피아노", "category": "음악", "tags": ["건반", "연주", "흑백"], "file": "piano.png", "w": 842, "h": 534},
    {"key": "speaker", "name": "스피커", "category": "음악", "tags": ["앰프", "소리", "빵빵"], "file": "speaker.png", "w": 678, "h": 842},
    {"key": "rockhand", "name": "락 손", "category": "음악", "tags": ["락앤롤", "메탈", "예"], "file": "rockhand.png", "w": 627, "h": 802},
    {"key": "amp", "name": "앰프", "category": "음악", "tags": ["기타앰프", "밴드", "볼륨"], "file": "amp.png", "w": 802, "h": 689},
    {"key": "strawberry", "name": "딸기", "category": "음식", "tags": ["달콤", "빨강", "과일"], "file": "strawberry.png", "w": 704, "h": 862},
    {"key": "cherry", "name": "체리", "category": "음식", "tags": ["빨강", "달콤", "과일"], "file": "cherry.png", "w": 668, "h": 779},
    {"key": "watermelon", "name": "수박", "category": "음식", "tags": ["여름", "시원", "과일"], "file": "watermelon.png", "w": 862, "h": 453},
    {"key": "icecream", "name": "아이스크림", "category": "음식", "tags": ["달콤", "여름", "디저트"], "file": "icecream.png", "w": 432, "h": 883},
    {"key": "donut", "name": "도넛", "category": "음식", "tags": ["달콤", "핑크", "디저트"], "file": "donut.png", "w": 862, "h": 862},
    {"key": "pizza", "name": "피자", "category": "음식", "tags": ["치즈", "야식", "맛있다"], "file": "pizza.png", "w": 802, "h": 943},
    {"key": "burger", "name": "햄버거", "category": "음식", "tags": ["야식", "맛있다", "패스트푸드"], "file": "burger.png", "w": 791, "h": 771},
    {"key": "coffee", "name": "커피", "category": "음식", "tags": ["카페", "따뜻", "아침"], "file": "coffee.png", "w": 726, "h": 785},
    {"key": "lemon", "name": "레몬", "category": "음식", "tags": ["상큼", "노랑", "과일"], "file": "lemon.png", "w": 822, "h": 668},
    {"key": "egg", "name": "계란 후라이", "category": "음식", "tags": ["아침", "노른자", "귀여워"], "file": "egg.png", "w": 780, "h": 757},
    {"key": "txt-love", "name": "LOVE", "category": "글자", "tags": ["사랑", "영문", "배지"], "file": "txt-love.png", "w": 904, "h": 392},
    {"key": "txt-rock", "name": "ROCK", "category": "글자", "tags": ["락", "밴드", "영문"], "file": "txt-rock.png", "w": 862, "h": 452},
    {"key": "txt-wow", "name": "WOW!", "category": "글자", "tags": ["놀라워", "영문", "배지"], "file": "txt-wow.png", "w": 982, "h": 1006},
    {"key": "txt-ok", "name": "OK!", "category": "글자", "tags": ["좋아", "영문", "배지"], "file": "txt-ok.png", "w": 862, "h": 862},
    {"key": "txt-live", "name": "LIVE", "category": "글자", "tags": ["공연", "라이브", "영문"], "file": "txt-live.png", "w": 862, "h": 412},
    {"key": "txt-band", "name": "BAND", "category": "글자", "tags": ["밴드", "음악", "영문"], "file": "txt-band.png", "w": 904, "h": 392},
    {"key": "txt-yeah", "name": "YEAH!", "category": "글자", "tags": ["신나", "영문", "배지"], "file": "txt-yeah.png", "w": 904, "h": 452},
    {"key": "txt-best", "name": "최고", "category": "글자", "tags": ["최고", "한글", "칭찬"], "file": "txt-best.png", "w": 862, "h": 494},
    {"key": "txt-good", "name": "굿", "category": "글자", "tags": ["굿", "한글", "칭찬"], "file": "txt-good.png", "w": 862, "h": 862},
    {"key": "txt-fighting", "name": "화이팅", "category": "글자", "tags": ["응원", "한글", "힘내"], "file": "txt-fighting.png", "w": 944, "h": 412},
    {"key": "txt-cute", "name": "귀여워", "category": "글자", "tags": ["귀여워", "한글", "하트"], "file": "txt-cute.png", "w": 966, "h": 846},
    {"key": "txt-daebak", "name": "대박", "category": "글자", "tags": ["대박", "한글", "놀라워"], "file": "txt-daebak.png", "w": 1024, "h": 1024},
    {"key": "ghost", "name": "유령", "category": "캐릭터·자연", "tags": ["귀신", "할로윈", "귀여워"], "file": "ghost.png", "w": 556, "h": 791},
    {"key": "alien", "name": "외계인", "category": "캐릭터·자연", "tags": ["우주", "초록", "UFO"], "file": "alien.png", "w": 596, "h": 782},
    {"key": "robot", "name": "로봇", "category": "캐릭터·자연", "tags": ["기계", "삐빅", "귀여워"], "file": "robot.png", "w": 760, "h": 801},
    {"key": "planet", "name": "행성", "category": "캐릭터·자연", "tags": ["우주", "토성", "보라"], "file": "planet.png", "w": 940, "h": 556},
    {"key": "rocket", "name": "로켓", "category": "캐릭터·자연", "tags": ["우주", "발사", "모험"], "file": "rocket.png", "w": 576, "h": 843},
    {"key": "flower", "name": "꽃", "category": "캐릭터·자연", "tags": ["데이지", "봄", "핑크"], "file": "flower.png", "w": 986, "h": 986},
    {"key": "cactus", "name": "선인장", "category": "캐릭터·자연", "tags": ["식물", "초록", "사막"], "file": "cactus.png", "w": 618, "h": 801},
    {"key": "mushroom", "name": "버섯", "category": "캐릭터·자연", "tags": ["숲", "빨강", "귀여워"], "file": "mushroom.png", "w": 802, "h": 709},
    {"key": "clover", "name": "네잎클로버", "category": "캐릭터·자연", "tags": ["행운", "초록", "럭키"], "file": "clover.png", "w": 766, "h": 811},
    {"key": "crown", "name": "왕관", "category": "캐릭터·자연", "tags": ["왕", "노랑", "최고"], "file": "crown.png", "w": 834, "h": 641},
    {"key": "bow", "name": "리본", "category": "캐릭터·자연", "tags": ["리본", "핑크", "선물"], "file": "bow.png", "w": 848, "h": 555},
    {"key": "smile", "name": "스마일", "category": "캐릭터·자연", "tags": ["웃음", "노랑", "해피"], "file": "smile.png", "w": 862, "h": 862},
    {"key": "fruit-apple", "name": "사과", "category": "과일", "tags": ["빨강", "과일", "입체"], "file": "fruit-apple.png", "w": 722, "h": 785},
    {"key": "fruit-pear", "name": "배", "category": "과일", "tags": ["노랑", "과일", "입체"], "file": "fruit-pear.png", "w": 578, "h": 870},
    {"key": "fruit-banana", "name": "바나나", "category": "과일", "tags": ["노랑", "과일", "입체"], "file": "fruit-banana.png", "w": 829, "h": 638},
    {"key": "fruit-grapes", "name": "포도", "category": "과일", "tags": ["보라", "과일", "입체"], "file": "fruit-grapes.png", "w": 548, "h": 805},
    {"key": "fruit-peach", "name": "복숭아", "category": "과일", "tags": ["핑크", "과일", "입체"], "file": "fruit-peach.png", "w": 730, "h": 825},
    {"key": "fruit-tangerine", "name": "귤", "category": "과일", "tags": ["주황", "과일", "입체"], "file": "fruit-tangerine.png", "w": 730, "h": 796},
    {"key": "fruit-pineapple", "name": "파인애플", "category": "과일", "tags": ["노랑", "여름", "입체"], "file": "fruit-pineapple.png", "w": 536, "h": 934},
    {"key": "fruit-kiwi", "name": "키위", "category": "과일", "tags": ["초록", "단면", "입체"], "file": "fruit-kiwi.png", "w": 862, "h": 862},
    {"key": "fruit-blueberry", "name": "블루베리", "category": "과일", "tags": ["파랑", "과일", "입체"], "file": "fruit-blueberry.png", "w": 699, "h": 637},
    {"key": "fruit-mango", "name": "망고", "category": "과일", "tags": ["주황", "열대", "입체"], "file": "fruit-mango.png", "w": 656, "h": 744},
    {"key": "fruit-avocado", "name": "아보카도", "category": "과일", "tags": ["초록", "단면", "입체"], "file": "fruit-avocado.png", "w": 596, "h": 863},
    {"key": "fruit-lemon-slice", "name": "레몬 단면", "category": "과일", "tags": ["노랑", "단면", "상큼"], "file": "fruit-lemon-slice.png", "w": 862, "h": 862},
    {"key": "fruit-plum", "name": "자두", "category": "과일", "tags": ["보라", "과일", "입체"], "file": "fruit-plum.png", "w": 730, "h": 824},
    {"key": "fruit-melon", "name": "멜론 조각", "category": "과일", "tags": ["주황", "여름", "입체"], "file": "fruit-melon.png", "w": 862, "h": 453},
    {"key": "fruit-strawberry", "name": "딸기", "category": "과일", "tags": ["빨강", "과일", "입체"], "file": "fruit-strawberry.png", "w": 704, "h": 862},
    {"key": "fruit-cherry", "name": "체리", "category": "과일", "tags": ["빨강", "과일", "입체"], "file": "fruit-cherry.png", "w": 668, "h": 785},
    {"key": "fruit-watermelon", "name": "수박 조각", "category": "과일", "tags": ["빨강", "여름", "입체"], "file": "fruit-watermelon.png", "w": 862, "h": 453},
    {"key": "fruit-lemon", "name": "레몬", "category": "과일", "tags": ["노랑", "과일", "입체"], "file": "fruit-lemon.png", "w": 822, "h": 678},
];
