// 기본 와펜 세트 목록 — tools/wappen-seed/build.mjs(또는 finish.py --reuse) 가 생성한다. 직접 수정하지 말 것.
// 벡터 항목은 tools/wappen-seed/designs.mjs 에서 코드로 그린 원본(CC0), kind:'raster' 항목은 tools/wappen-seed/raster.json 의 시트(제공자 소유)에서 잘라낸 것.
// 서버(functions/wappen-api.js admin_seed_items)와 관리자 화면이 같은 파일을 import.
export const SEED_VERSION = 3;
export const SEED_ITEMS = [
    {"key": "p-cherry", "name": "체리 패치", "category": "과일", "tags": ["체리", "빨강", "자수"], "file": "p-cherry.png", "w": 235, "h": 209, "kind": "raster"},
    {"key": "p-plaid-heart", "name": "체크 하트 핀", "category": "도형·기호", "tags": ["하트", "옷핀", "해골", "펑크", "자수"], "file": "p-plaid-heart.png", "w": 242, "h": 230, "kind": "raster"},
    {"key": "p-what-the-hell", "name": "what the hell 별", "category": "글자", "tags": ["별", "what the hell", "영문", "자수"], "file": "p-what-the-hell.png", "w": 199, "h": 229, "kind": "raster"},
    {"key": "p-checker-star", "name": "체커 별", "category": "도형·기호", "tags": ["별", "체크", "흑백", "자수"], "file": "p-checker-star.png", "w": 213, "h": 208, "kind": "raster"},
    {"key": "p-pink-guitar", "name": "핑크 기타", "category": "음악", "tags": ["기타", "일렉", "핑크", "밴드", "자수"], "file": "p-pink-guitar.png", "w": 230, "h": 261, "kind": "raster"},
    {"key": "p-pink-bolt", "name": "핑크 번개", "category": "도형·기호", "tags": ["번개", "핑크", "자수"], "file": "p-pink-bolt.png", "w": 155, "h": 211, "kind": "raster"},
    {"key": "p-pork-bowl", "name": "네기시오 부타동", "category": "음식", "tags": ["덮밥", "돈부리", "일식", "자수"], "file": "p-pork-bowl.png", "w": 256, "h": 200, "kind": "raster"},
    {"key": "p-orange-daisy", "name": "주황 데이지", "category": "캐릭터·자연", "tags": ["꽃", "데이지", "주황", "자수"], "file": "p-orange-daisy.png", "w": 173, "h": 205, "kind": "raster"},
    {"key": "p-get-lucky", "name": "GET LUCKY!", "category": "글자", "tags": ["get lucky", "행운", "영문", "자수"], "file": "p-get-lucky.png", "w": 222, "h": 181, "kind": "raster"},
    {"key": "p-blue-butterfly", "name": "파랑 나비", "category": "동물", "tags": ["나비", "파랑", "자수"], "file": "p-blue-butterfly.png", "w": 251, "h": 188, "kind": "raster"},
    {"key": "p-addiction", "name": "Addiction", "category": "글자", "tags": ["addiction", "하트", "영문", "자수"], "file": "p-addiction.png", "w": 284, "h": 166, "kind": "raster"},
    {"key": "p-three-stars", "name": "별 세 개", "category": "도형·기호", "tags": ["별", "반짝", "흰색", "자수"], "file": "p-three-stars.png", "w": 153, "h": 169, "kind": "raster"},
    {"key": "p-marigold", "name": "메리골드", "category": "캐릭터·자연", "tags": ["꽃", "메리골드", "주황", "자수"], "file": "p-marigold.png", "w": 191, "h": 179, "kind": "raster"},
    {"key": "p-moon-star", "name": "초승달과 별", "category": "캐릭터·자연", "tags": ["달", "별", "밤", "자수"], "file": "p-moon-star.png", "w": 177, "h": 174, "kind": "raster"},
    {"key": "p-stand-up", "name": "stand up!", "category": "글자", "tags": ["stand up", "영문", "자수"], "file": "p-stand-up.png", "w": 198, "h": 179, "kind": "raster"},
    {"key": "p-vinyl", "name": "LP 레코드", "category": "음악", "tags": ["LP", "레코드", "음반", "자수"], "file": "p-vinyl.png", "w": 211, "h": 182, "kind": "raster"},
    {"key": "p-wing-heart", "name": "날개 하트", "category": "도형·기호", "tags": ["하트", "별", "핑크", "자수"], "file": "p-wing-heart.png", "w": 251, "h": 150, "kind": "raster"},
    {"key": "p-flame", "name": "불꽃", "category": "도형·기호", "tags": ["불", "화염", "빨강", "자수"], "file": "p-flame.png", "w": 173, "h": 192, "kind": "raster"},
    {"key": "p-burst", "name": "펑 폭발", "category": "도형·기호", "tags": ["폭발", "번쩍", "파랑", "자수"], "file": "p-burst.png", "w": 207, "h": 167, "kind": "raster"},
    {"key": "p-loud-hot-crazy", "name": "LOUD! HOT! CRAZY!", "category": "글자", "tags": ["loud", "hot", "crazy", "영문", "자수"], "file": "p-loud-hot-crazy.png", "w": 228, "h": 181, "kind": "raster"},
    {"key": "p-bandage-heart", "name": "반창고 하트", "category": "도형·기호", "tags": ["하트", "반창고", "체크", "자수"], "file": "p-bandage-heart.png", "w": 199, "h": 171, "kind": "raster"},
    {"key": "p-sunset", "name": "석양", "category": "캐릭터·자연", "tags": ["노을", "바다", "해", "자수"], "file": "p-sunset.png", "w": 235, "h": 159, "kind": "raster"},
    {"key": "p-mountain", "name": "산과 해", "category": "캐릭터·자연", "tags": ["산", "해", "자연", "자수"], "file": "p-mountain.png", "w": 254, "h": 146, "kind": "raster"},
    {"key": "p-dolphin", "name": "돌고래", "category": "동물", "tags": ["돌고래", "바다", "파랑", "자수"], "file": "p-dolphin.png", "w": 214, "h": 176, "kind": "raster"},
    {"key": "p-pink-flower", "name": "분홍 꽃", "category": "캐릭터·자연", "tags": ["꽃", "분홍", "자수"], "file": "p-pink-flower.png", "w": 164, "h": 159, "kind": "raster"},
    {"key": "p-zebra-star", "name": "얼룩 별", "category": "도형·기호", "tags": ["별", "줄무늬", "흑백", "자수"], "file": "p-zebra-star.png", "w": 182, "h": 169, "kind": "raster"},
    {"key": "p-saturn", "name": "토성", "category": "캐릭터·자연", "tags": ["토성", "행성", "우주", "자수"], "file": "p-saturn.png", "w": 222, "h": 146, "kind": "raster"},
    {"key": "p-black-cat", "name": "검은 고양이", "category": "동물", "tags": ["고양이", "검정", "자수"], "file": "p-black-cat.png", "w": 185, "h": 156, "kind": "raster"},
    {"key": "p-dice", "name": "빨간 주사위", "category": "도형·기호", "tags": ["주사위", "빨강", "게임", "자수"], "file": "p-dice.png", "w": 196, "h": 158, "kind": "raster"},
    {"key": "p-music-note", "name": "핑크 음표", "category": "음악", "tags": ["음표", "음악", "핑크", "자수"], "file": "p-music-note.png", "w": 134, "h": 162, "kind": "raster"},
    {"key": "p2-cherry-heart", "name": "체리 하트", "category": "도형·기호", "tags": ["하트", "체리", "핑크", "반짝", "자수"], "file": "p2-cherry-heart.png", "w": 400, "h": 380, "kind": "raster"},
    {"key": "p2-orbit-star", "name": "궤도 별", "category": "도형·기호", "tags": ["별", "궤도", "파랑", "반짝", "자수"], "file": "p2-orbit-star.png", "w": 418, "h": 413, "kind": "raster"},
    {"key": "p2-smile-daisy", "name": "스마일 데이지", "category": "캐릭터·자연", "tags": ["꽃", "데이지", "스마일", "자수"], "file": "p2-smile-daisy.png", "w": 404, "h": 419, "kind": "raster"},
    {"key": "p2-bolt-flame", "name": "번개 불꽃", "category": "도형·기호", "tags": ["불", "번개", "빨강", "자수"], "file": "p2-bolt-flame.png", "w": 356, "h": 446, "kind": "raster"},
    {"key": "p2-purple-planet", "name": "보라 행성", "category": "캐릭터·자연", "tags": ["행성", "토성", "우주", "보라", "자수"], "file": "p2-purple-planet.png", "w": 376, "h": 319, "kind": "raster"},
    {"key": "p2-wave", "name": "파도", "category": "캐릭터·자연", "tags": ["파도", "바다", "파랑", "자수"], "file": "p2-wave.png", "w": 409, "h": 353, "kind": "raster"},
];
